// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using uFrame.IOC;
using uFrame.Kernel;
using uFrame.MVVM;


public class DummySubSystemLoaderBase : uFrame.Kernel.SystemLoader {
    
    private TestController _TestController;
    
    [uFrame.IOC.InjectAttribute()]
    public virtual TestController TestController {
        get {
            if (_TestController==null) {
                _TestController = Container.CreateInstance(typeof(TestController)) as TestController;;
            }
            return _TestController;
        }
        set {
            _TestController = value;
        }
    }
    
    public override void Load() {
        Container.RegisterViewModelManager<TestViewModel>(new ViewModelManager<TestViewModel>());
        Container.RegisterController<TestController>(TestController);
    }
}
